// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Sandbox struct {
	ID             string         `json:"id"`
	ContainerID    sql.NullString `json:"container_id"`
	HostOriginDir  string         `json:"host_origin_dir"`
	SandboxWorkDir string         `json:"sandbox_work_dir"`
	ImageName      string         `json:"image_name"`
	DnsDomain      sql.NullString `json:"dns_domain"`
	EnvFile        sql.NullString `json:"env_file"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}
