// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	DeleteSandbox(ctx context.Context, id string) error
	GetSandbox(ctx context.Context, id string) (Sandbox, error)
	GetSandboxesByImage(ctx context.Context, imageName string) ([]Sandbox, error)
	ListSandboxes(ctx context.Context) ([]Sandbox, error)
	UpdateContainerID(ctx context.Context, arg UpdateContainerIDParams) error
	UpsertSandbox(ctx context.Context, arg UpsertSandboxParams) error
}

var _ Querier = (*Queries)(nil)
