#!/bin/zsh
set -e

# Redirect mise to store everything in our shared host mount.
export MISE_DATA_DIR="/opt/tool-cache/mise"
export MISE_CONFIG_DIR="/opt/tool-cache/mise/config"
export MISE_CACHE_DIR="/opt/tool-cache/mise/cache"
export MISE_STATE_DIR="/opt/tool-cache/mise/state"

has_project_file() {
    local filename="$1"

    find /app \
        \( -type d \( \
            -name .git -o \
            -name node_modules -o \
            -name vendor -o \
            -name .venv -o \
            -name venv -o \
            -name __pycache__ -o \
            -name .mypy_cache -o \
            -name .pytest_cache \
        \) -prune \) \
        -o \( -type f -name "$filename" -print -quit \) | grep -q .
}

# Automatically install runtimes defined in .tool-versions or mise.toml.
if [ -f ".tool-versions" ] || [ -f "mise.toml" ]; then
    echo "Detecting runtimes from config..."
    if [ -f "mise.toml" ]; then
        mise trust ./mise.toml
    fi
    mise install -y
    eval "$(mise activate zsh)"
else
    # Fallback: if no config file, manually inject based on file detection.
    has_project_file "package.json" && mise use --global node@latest
    has_project_file "go.mod" && mise use --global go@latest
    has_project_file "requirements.txt" && mise use --global python@3.11
    eval "$(mise activate zsh)"
fi

# Set language-specific caches within the same shared mount.
export GOMODCACHE="$MISE_DATA_DIR/go/mod"
export GOCACHE="$MISE_DATA_DIR/go/build"
export PIP_CACHE_DIR="/opt/tool-cache/python/pip"

{
  echo "# Generated by mise.sh"
  echo "export PATH=\"$PATH\""
  echo "export PNPM_HOME=\"$PNPM_HOME\""
  echo "export GOCACHE=\"$GOCACHE\""
  echo "export GOMODCACHE=\"$GOMODCACHE\""
  echo "export PIP_CACHE_DIR=\"$PIP_CACHE_DIR\""
  echo "export MISE_DATA_DIR=\"$MISE_DATA_DIR\""
  echo "export MISE_CONFIG_DIR=\"$MISE_CONFIG_DIR\""
  echo "export MISE_CACHE_DIR=\"$MISE_CACHE_DIR\""
  echo "export MISE_STATE_DIR=\"$MISE_STATE_DIR\""
} > /etc/shared_env.sh

chmod 644 /etc/shared_env.sh

exec "$@"
