// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/daemon/daemonpb/daemon.proto

package daemonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{2}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GitRepo       string                 `protobuf:"bytes,1,opt,name=git_repo,json=gitRepo,proto3" json:"git_repo,omitempty"`
	GitBranch     string                 `protobuf:"bytes,2,opt,name=git_branch,json=gitBranch,proto3" json:"git_branch,omitempty"`
	GitCommit     string                 `protobuf:"bytes,3,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	BuildTime     string                 `protobuf:"bytes,4,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	BuildInfoJson []byte                 `protobuf:"bytes,5,opt,name=build_info_json,json=buildInfoJson,proto3" json:"build_info_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *VersionResponse) GetGitRepo() string {
	if x != nil {
		return x.GitRepo
	}
	return ""
}

func (x *VersionResponse) GetGitBranch() string {
	if x != nil {
		return x.GitBranch
	}
	return ""
}

func (x *VersionResponse) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *VersionResponse) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *VersionResponse) GetBuildInfoJson() []byte {
	if x != nil {
		return x.BuildInfoJson
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{5}
}

type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *IDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LogSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSandboxResponse) Reset() {
	*x = LogSandboxResponse{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSandboxResponse) ProtoMessage() {}

func (x *LogSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSandboxResponse.ProtoReflect.Descriptor instead.
func (*LogSandboxResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *LogSandboxResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListSandboxesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{8}
}

type ListSandboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoxesJson     []byte                 `protobuf:"bytes,1,opt,name=boxes_json,json=boxesJson,proto3" json:"boxes_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *ListSandboxesResponse) GetBoxesJson() []byte {
	if x != nil {
		return x.BoxesJson
	}
	return nil
}

type GetSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoxJson       []byte                 `protobuf:"bytes,1,opt,name=box_json,json=boxJson,proto3" json:"box_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxResponse) Reset() {
	*x = GetSandboxResponse{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxResponse) ProtoMessage() {}

func (x *GetSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *GetSandboxResponse) GetBoxJson() []byte {
	if x != nil {
		return x.BoxJson
	}
	return nil
}

type StartSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SshAgent      bool                   `protobuf:"varint,2,opt,name=ssh_agent,json=sshAgent,proto3" json:"ssh_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSandboxRequest) Reset() {
	*x = StartSandboxRequest{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSandboxRequest) ProtoMessage() {}

func (x *StartSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSandboxRequest.ProtoReflect.Descriptor instead.
func (*StartSandboxRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *StartSandboxRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartSandboxRequest) GetSshAgent() bool {
	if x != nil {
		return x.SshAgent
	}
	return false
}

type SyncHostGitMirrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MirrorPath    string                 `protobuf:"bytes,1,opt,name=mirror_path,json=mirrorPath,proto3" json:"mirror_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncHostGitMirrorResponse) Reset() {
	*x = SyncHostGitMirrorResponse{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncHostGitMirrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncHostGitMirrorResponse) ProtoMessage() {}

func (x *SyncHostGitMirrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncHostGitMirrorResponse.ProtoReflect.Descriptor instead.
func (*SyncHostGitMirrorResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *SyncHostGitMirrorResponse) GetMirrorPath() string {
	if x != nil {
		return x.MirrorPath
	}
	return ""
}

type ResolveAgentLaunchEnvRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Agent                string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	EnvFile              string                 `protobuf:"bytes,2,opt,name=env_file,json=envFile,proto3" json:"env_file,omitempty"`
	ProfileName          string                 `protobuf:"bytes,3,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	ProfileEnv           *EnvPolicy             `protobuf:"bytes,4,opt,name=profile_env,json=profileEnv,proto3" json:"profile_env,omitempty"`
	ProfileEnvConfigured bool                   `protobuf:"varint,5,opt,name=profile_env_configured,json=profileEnvConfigured,proto3" json:"profile_env_configured,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResolveAgentLaunchEnvRequest) Reset() {
	*x = ResolveAgentLaunchEnvRequest{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAgentLaunchEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAgentLaunchEnvRequest) ProtoMessage() {}

func (x *ResolveAgentLaunchEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAgentLaunchEnvRequest.ProtoReflect.Descriptor instead.
func (*ResolveAgentLaunchEnvRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *ResolveAgentLaunchEnvRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *ResolveAgentLaunchEnvRequest) GetEnvFile() string {
	if x != nil {
		return x.EnvFile
	}
	return ""
}

func (x *ResolveAgentLaunchEnvRequest) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *ResolveAgentLaunchEnvRequest) GetProfileEnv() *EnvPolicy {
	if x != nil {
		return x.ProfileEnv
	}
	return nil
}

func (x *ResolveAgentLaunchEnvRequest) GetProfileEnvConfigured() bool {
	if x != nil {
		return x.ProfileEnvConfigured
	}
	return false
}

type ResolveAgentLaunchEnvResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           map[string]string      `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAgentLaunchEnvResponse) Reset() {
	*x = ResolveAgentLaunchEnvResponse{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAgentLaunchEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAgentLaunchEnvResponse) ProtoMessage() {}

func (x *ResolveAgentLaunchEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAgentLaunchEnvResponse.ProtoReflect.Descriptor instead.
func (*ResolveAgentLaunchEnvResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *ResolveAgentLaunchEnvResponse) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type EnvPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*EnvFileRef          `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Vars          []*EnvVarRule          `protobuf:"bytes,2,rep,name=vars,proto3" json:"vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvPolicy) Reset() {
	*x = EnvPolicy{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvPolicy) ProtoMessage() {}

func (x *EnvPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvPolicy.ProtoReflect.Descriptor instead.
func (*EnvPolicy) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *EnvPolicy) GetFiles() []*EnvFileRef {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *EnvPolicy) GetVars() []*EnvVarRule {
	if x != nil {
		return x.Vars
	}
	return nil
}

type EnvFileRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvFileRef) Reset() {
	*x = EnvFileRef{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvFileRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvFileRef) ProtoMessage() {}

func (x *EnvFileRef) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvFileRef.ProtoReflect.Descriptor instead.
func (*EnvFileRef) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *EnvFileRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EnvFileRef) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type EnvVarRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVarRule) Reset() {
	*x = EnvVarRule{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVarRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVarRule) ProtoMessage() {}

func (x *EnvVarRule) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVarRule.ProtoReflect.Descriptor instead.
func (*EnvVarRule) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *EnvVarRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVarRule) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type ExportImageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DestinationPath string                 `protobuf:"bytes,2,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExportImageRequest) Reset() {
	*x = ExportImageRequest{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportImageRequest) ProtoMessage() {}

func (x *ExportImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportImageRequest.ProtoReflect.Descriptor instead.
func (*ExportImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *ExportImageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExportImageRequest) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *StatsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatsJson     []byte                 `protobuf:"bytes,1,opt,name=stats_json,json=statsJson,proto3" json:"stats_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *StatsResponse) GetStatsJson() []byte {
	if x != nil {
		return x.StatsJson
	}
	return nil
}

type SharedCacheConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mise          bool                   `protobuf:"varint,1,opt,name=mise,proto3" json:"mise,omitempty"`
	Apk           bool                   `protobuf:"varint,2,opt,name=apk,proto3" json:"apk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedCacheConfig) Reset() {
	*x = SharedCacheConfig{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedCacheConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedCacheConfig) ProtoMessage() {}

func (x *SharedCacheConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedCacheConfig.ProtoReflect.Descriptor instead.
func (*SharedCacheConfig) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{21}
}

func (x *SharedCacheConfig) GetMise() bool {
	if x != nil {
		return x.Mise
	}
	return false
}

func (x *SharedCacheConfig) GetApk() bool {
	if x != nil {
		return x.Apk
	}
	return false
}

type CreateSandboxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CloneFromDir   string                 `protobuf:"bytes,2,opt,name=clone_from_dir,json=cloneFromDir,proto3" json:"clone_from_dir,omitempty"`
	ImageName      string                 `protobuf:"bytes,3,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	EnvFile        string                 `protobuf:"bytes,4,opt,name=env_file,json=envFile,proto3" json:"env_file,omitempty"`
	Agent          string                 `protobuf:"bytes,5,opt,name=agent,proto3" json:"agent,omitempty"`
	SshAgent       bool                   `protobuf:"varint,6,opt,name=ssh_agent,json=sshAgent,proto3" json:"ssh_agent,omitempty"`
	Username       string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Uid            string                 `protobuf:"bytes,8,opt,name=uid,proto3" json:"uid,omitempty"`
	AllowedDomains []string               `protobuf:"bytes,9,rep,name=allowed_domains,json=allowedDomains,proto3" json:"allowed_domains,omitempty"`
	Volumes        []string               `protobuf:"bytes,10,rep,name=volumes,proto3" json:"volumes,omitempty"`
	SharedCaches   *SharedCacheConfig     `protobuf:"bytes,11,opt,name=shared_caches,json=sharedCaches,proto3" json:"shared_caches,omitempty"`
	Cpus           int32                  `protobuf:"varint,12,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Memory         int32                  `protobuf:"varint,13,opt,name=memory,proto3" json:"memory,omitempty"`
	ProfileName    string                 `protobuf:"bytes,14,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{22}
}

func (x *CreateSandboxRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateSandboxRequest) GetCloneFromDir() string {
	if x != nil {
		return x.CloneFromDir
	}
	return ""
}

func (x *CreateSandboxRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *CreateSandboxRequest) GetEnvFile() string {
	if x != nil {
		return x.EnvFile
	}
	return ""
}

func (x *CreateSandboxRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *CreateSandboxRequest) GetSshAgent() bool {
	if x != nil {
		return x.SshAgent
	}
	return false
}

func (x *CreateSandboxRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateSandboxRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CreateSandboxRequest) GetAllowedDomains() []string {
	if x != nil {
		return x.AllowedDomains
	}
	return nil
}

func (x *CreateSandboxRequest) GetVolumes() []string {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *CreateSandboxRequest) GetSharedCaches() *SharedCacheConfig {
	if x != nil {
		return x.SharedCaches
	}
	return nil
}

func (x *CreateSandboxRequest) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *CreateSandboxRequest) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *CreateSandboxRequest) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

type CreateSandboxResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*CreateSandboxResponse_Progress
	//	*CreateSandboxResponse_BoxJson
	//	*CreateSandboxResponse_Error
	Event         isCreateSandboxResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{23}
}

func (x *CreateSandboxResponse) GetEvent() isCreateSandboxResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CreateSandboxResponse) GetProgress() string {
	if x != nil {
		if x, ok := x.Event.(*CreateSandboxResponse_Progress); ok {
			return x.Progress
		}
	}
	return ""
}

func (x *CreateSandboxResponse) GetBoxJson() []byte {
	if x != nil {
		if x, ok := x.Event.(*CreateSandboxResponse_BoxJson); ok {
			return x.BoxJson
		}
	}
	return nil
}

func (x *CreateSandboxResponse) GetError() string {
	if x != nil {
		if x, ok := x.Event.(*CreateSandboxResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isCreateSandboxResponse_Event interface {
	isCreateSandboxResponse_Event()
}

type CreateSandboxResponse_Progress struct {
	Progress string `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type CreateSandboxResponse_BoxJson struct {
	BoxJson []byte `protobuf:"bytes,2,opt,name=box_json,json=boxJson,proto3,oneof"`
}

type CreateSandboxResponse_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*CreateSandboxResponse_Progress) isCreateSandboxResponse_Event() {}

func (*CreateSandboxResponse_BoxJson) isCreateSandboxResponse_Event() {}

func (*CreateSandboxResponse_Error) isCreateSandboxResponse_Event() {}

type EnsureImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageName     string                 `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureImageRequest) Reset() {
	*x = EnsureImageRequest{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureImageRequest) ProtoMessage() {}

func (x *EnsureImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureImageRequest.ProtoReflect.Descriptor instead.
func (*EnsureImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{24}
}

func (x *EnsureImageRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type EnsureImageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*EnsureImageResponse_Progress
	//	*EnsureImageResponse_Error
	//	*EnsureImageResponse_Ok
	Event         isEnsureImageResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureImageResponse) Reset() {
	*x = EnsureImageResponse{}
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureImageResponse) ProtoMessage() {}

func (x *EnsureImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_daemonpb_daemon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureImageResponse.ProtoReflect.Descriptor instead.
func (*EnsureImageResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP(), []int{25}
}

func (x *EnsureImageResponse) GetEvent() isEnsureImageResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EnsureImageResponse) GetProgress() []byte {
	if x != nil {
		if x, ok := x.Event.(*EnsureImageResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *EnsureImageResponse) GetError() string {
	if x != nil {
		if x, ok := x.Event.(*EnsureImageResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *EnsureImageResponse) GetOk() bool {
	if x != nil {
		if x, ok := x.Event.(*EnsureImageResponse_Ok); ok {
			return x.Ok
		}
	}
	return false
}

type isEnsureImageResponse_Event interface {
	isEnsureImageResponse_Event()
}

type EnsureImageResponse_Progress struct {
	Progress []byte `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type EnsureImageResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type EnsureImageResponse_Ok struct {
	Ok bool `protobuf:"varint,3,opt,name=ok,proto3,oneof"`
}

func (*EnsureImageResponse_Progress) isEnsureImageResponse_Event() {}

func (*EnsureImageResponse_Error) isEnsureImageResponse_Event() {}

func (*EnsureImageResponse_Ok) isEnsureImageResponse_Event() {}

var File_internal_daemon_daemonpb_daemon_proto protoreflect.FileDescriptor

const file_internal_daemon_daemonpb_daemon_proto_rawDesc = "" +
	"\n" +
	"%internal/daemon/daemonpb/daemon.proto\x12\x0esand.daemon.v1\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x10\n" +
	"\x0eVersionRequest\"\xb1\x01\n" +
	"\x0fVersionResponse\x12\x19\n" +
	"\bgit_repo\x18\x01 \x01(\tR\agitRepo\x12\x1d\n" +
	"\n" +
	"git_branch\x18\x02 \x01(\tR\tgitBranch\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x03 \x01(\tR\tgitCommit\x12\x1d\n" +
	"\n" +
	"build_time\x18\x04 \x01(\tR\tbuildTime\x12&\n" +
	"\x0fbuild_info_json\x18\x05 \x01(\fR\rbuildInfoJson\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x11\n" +
	"\x0fShutdownRequest\"\x1b\n" +
	"\tIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x12LogSandboxResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x16\n" +
	"\x14ListSandboxesRequest\"6\n" +
	"\x15ListSandboxesResponse\x12\x1d\n" +
	"\n" +
	"boxes_json\x18\x01 \x01(\fR\tboxesJson\"/\n" +
	"\x12GetSandboxResponse\x12\x19\n" +
	"\bbox_json\x18\x01 \x01(\fR\aboxJson\"B\n" +
	"\x13StartSandboxRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tssh_agent\x18\x02 \x01(\bR\bsshAgent\"<\n" +
	"\x19SyncHostGitMirrorResponse\x12\x1f\n" +
	"\vmirror_path\x18\x01 \x01(\tR\n" +
	"mirrorPath\"\xe4\x01\n" +
	"\x1cResolveAgentLaunchEnvRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12\x19\n" +
	"\benv_file\x18\x02 \x01(\tR\aenvFile\x12!\n" +
	"\fprofile_name\x18\x03 \x01(\tR\vprofileName\x12:\n" +
	"\vprofile_env\x18\x04 \x01(\v2\x19.sand.daemon.v1.EnvPolicyR\n" +
	"profileEnv\x124\n" +
	"\x16profile_env_configured\x18\x05 \x01(\bR\x14profileEnvConfigured\"\xa1\x01\n" +
	"\x1dResolveAgentLaunchEnvResponse\x12H\n" +
	"\x03env\x18\x01 \x03(\v26.sand.daemon.v1.ResolveAgentLaunchEnvResponse.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\tEnvPolicy\x120\n" +
	"\x05files\x18\x01 \x03(\v2\x1a.sand.daemon.v1.EnvFileRefR\x05files\x12.\n" +
	"\x04vars\x18\x02 \x03(\v2\x1a.sand.daemon.v1.EnvVarRuleR\x04vars\"6\n" +
	"\n" +
	"EnvFileRef\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\"6\n" +
	"\n" +
	"EnvVarRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\"O\n" +
	"\x12ExportImageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10destination_path\x18\x02 \x01(\tR\x0fdestinationPath\" \n" +
	"\fStatsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\".\n" +
	"\rStatsResponse\x12\x1d\n" +
	"\n" +
	"stats_json\x18\x01 \x01(\fR\tstatsJson\"9\n" +
	"\x11SharedCacheConfig\x12\x12\n" +
	"\x04mise\x18\x01 \x01(\bR\x04mise\x12\x10\n" +
	"\x03apk\x18\x02 \x01(\bR\x03apk\"\xc1\x03\n" +
	"\x14CreateSandboxRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0eclone_from_dir\x18\x02 \x01(\tR\fcloneFromDir\x12\x1d\n" +
	"\n" +
	"image_name\x18\x03 \x01(\tR\timageName\x12\x19\n" +
	"\benv_file\x18\x04 \x01(\tR\aenvFile\x12\x14\n" +
	"\x05agent\x18\x05 \x01(\tR\x05agent\x12\x1b\n" +
	"\tssh_agent\x18\x06 \x01(\bR\bsshAgent\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\x12\x10\n" +
	"\x03uid\x18\b \x01(\tR\x03uid\x12'\n" +
	"\x0fallowed_domains\x18\t \x03(\tR\x0eallowedDomains\x12\x18\n" +
	"\avolumes\x18\n" +
	" \x03(\tR\avolumes\x12F\n" +
	"\rshared_caches\x18\v \x01(\v2!.sand.daemon.v1.SharedCacheConfigR\fsharedCaches\x12\x12\n" +
	"\x04cpus\x18\f \x01(\x05R\x04cpus\x12\x16\n" +
	"\x06memory\x18\r \x01(\x05R\x06memory\x12!\n" +
	"\fprofile_name\x18\x0e \x01(\tR\vprofileName\"s\n" +
	"\x15CreateSandboxResponse\x12\x1c\n" +
	"\bprogress\x18\x01 \x01(\tH\x00R\bprogress\x12\x1b\n" +
	"\bbox_json\x18\x02 \x01(\fH\x00R\aboxJson\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\a\n" +
	"\x05event\"3\n" +
	"\x12EnsureImageRequest\x12\x1d\n" +
	"\n" +
	"image_name\x18\x01 \x01(\tR\timageName\"f\n" +
	"\x13EnsureImageResponse\x12\x1c\n" +
	"\bprogress\x18\x01 \x01(\fH\x00R\bprogress\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x12\x10\n" +
	"\x02ok\x18\x03 \x01(\bH\x00R\x02okB\a\n" +
	"\x05event2\xb4\n" +
	"\n" +
	"\rDaemonService\x12A\n" +
	"\x04Ping\x12\x1b.sand.daemon.v1.PingRequest\x1a\x1c.sand.daemon.v1.PingResponse\x12J\n" +
	"\aVersion\x12\x1e.sand.daemon.v1.VersionRequest\x1a\x1f.sand.daemon.v1.VersionResponse\x12K\n" +
	"\bShutdown\x12\x1f.sand.daemon.v1.ShutdownRequest\x1a\x1e.sand.daemon.v1.StatusResponse\x12K\n" +
	"\n" +
	"LogSandbox\x12\x19.sand.daemon.v1.IDRequest\x1a\".sand.daemon.v1.LogSandboxResponse\x12\\\n" +
	"\rListSandboxes\x12$.sand.daemon.v1.ListSandboxesRequest\x1a%.sand.daemon.v1.ListSandboxesResponse\x12K\n" +
	"\n" +
	"GetSandbox\x12\x19.sand.daemon.v1.IDRequest\x1a\".sand.daemon.v1.GetSandboxResponse\x12J\n" +
	"\rRemoveSandbox\x12\x19.sand.daemon.v1.IDRequest\x1a\x1e.sand.daemon.v1.StatusResponse\x12H\n" +
	"\vStopSandbox\x12\x19.sand.daemon.v1.IDRequest\x1a\x1e.sand.daemon.v1.StatusResponse\x12S\n" +
	"\fStartSandbox\x12#.sand.daemon.v1.StartSandboxRequest\x1a\x1e.sand.daemon.v1.StatusResponse\x12Y\n" +
	"\x11SyncHostGitMirror\x12\x19.sand.daemon.v1.IDRequest\x1a).sand.daemon.v1.SyncHostGitMirrorResponse\x12t\n" +
	"\x15ResolveAgentLaunchEnv\x12,.sand.daemon.v1.ResolveAgentLaunchEnvRequest\x1a-.sand.daemon.v1.ResolveAgentLaunchEnvResponse\x12Q\n" +
	"\vExportImage\x12\".sand.daemon.v1.ExportImageRequest\x1a\x1e.sand.daemon.v1.StatusResponse\x12D\n" +
	"\x05Stats\x12\x1c.sand.daemon.v1.StatsRequest\x1a\x1d.sand.daemon.v1.StatsResponse\x12@\n" +
	"\x03VSC\x12\x19.sand.daemon.v1.IDRequest\x1a\x1e.sand.daemon.v1.StatusResponse\x12^\n" +
	"\rCreateSandbox\x12$.sand.daemon.v1.CreateSandboxRequest\x1a%.sand.daemon.v1.CreateSandboxResponse0\x01\x12X\n" +
	"\vEnsureImage\x12\".sand.daemon.v1.EnsureImageRequest\x1a#.sand.daemon.v1.EnsureImageResponse0\x01B3Z1github.com/banksean/sand/internal/daemon/daemonpbb\x06proto3"

var (
	file_internal_daemon_daemonpb_daemon_proto_rawDescOnce sync.Once
	file_internal_daemon_daemonpb_daemon_proto_rawDescData []byte
)

func file_internal_daemon_daemonpb_daemon_proto_rawDescGZIP() []byte {
	file_internal_daemon_daemonpb_daemon_proto_rawDescOnce.Do(func() {
		file_internal_daemon_daemonpb_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_daemon_daemonpb_daemon_proto_rawDesc), len(file_internal_daemon_daemonpb_daemon_proto_rawDesc)))
	})
	return file_internal_daemon_daemonpb_daemon_proto_rawDescData
}

var file_internal_daemon_daemonpb_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_internal_daemon_daemonpb_daemon_proto_goTypes = []any{
	(*PingRequest)(nil),                   // 0: sand.daemon.v1.PingRequest
	(*PingResponse)(nil),                  // 1: sand.daemon.v1.PingResponse
	(*VersionRequest)(nil),                // 2: sand.daemon.v1.VersionRequest
	(*VersionResponse)(nil),               // 3: sand.daemon.v1.VersionResponse
	(*StatusResponse)(nil),                // 4: sand.daemon.v1.StatusResponse
	(*ShutdownRequest)(nil),               // 5: sand.daemon.v1.ShutdownRequest
	(*IDRequest)(nil),                     // 6: sand.daemon.v1.IDRequest
	(*LogSandboxResponse)(nil),            // 7: sand.daemon.v1.LogSandboxResponse
	(*ListSandboxesRequest)(nil),          // 8: sand.daemon.v1.ListSandboxesRequest
	(*ListSandboxesResponse)(nil),         // 9: sand.daemon.v1.ListSandboxesResponse
	(*GetSandboxResponse)(nil),            // 10: sand.daemon.v1.GetSandboxResponse
	(*StartSandboxRequest)(nil),           // 11: sand.daemon.v1.StartSandboxRequest
	(*SyncHostGitMirrorResponse)(nil),     // 12: sand.daemon.v1.SyncHostGitMirrorResponse
	(*ResolveAgentLaunchEnvRequest)(nil),  // 13: sand.daemon.v1.ResolveAgentLaunchEnvRequest
	(*ResolveAgentLaunchEnvResponse)(nil), // 14: sand.daemon.v1.ResolveAgentLaunchEnvResponse
	(*EnvPolicy)(nil),                     // 15: sand.daemon.v1.EnvPolicy
	(*EnvFileRef)(nil),                    // 16: sand.daemon.v1.EnvFileRef
	(*EnvVarRule)(nil),                    // 17: sand.daemon.v1.EnvVarRule
	(*ExportImageRequest)(nil),            // 18: sand.daemon.v1.ExportImageRequest
	(*StatsRequest)(nil),                  // 19: sand.daemon.v1.StatsRequest
	(*StatsResponse)(nil),                 // 20: sand.daemon.v1.StatsResponse
	(*SharedCacheConfig)(nil),             // 21: sand.daemon.v1.SharedCacheConfig
	(*CreateSandboxRequest)(nil),          // 22: sand.daemon.v1.CreateSandboxRequest
	(*CreateSandboxResponse)(nil),         // 23: sand.daemon.v1.CreateSandboxResponse
	(*EnsureImageRequest)(nil),            // 24: sand.daemon.v1.EnsureImageRequest
	(*EnsureImageResponse)(nil),           // 25: sand.daemon.v1.EnsureImageResponse
	nil,                                   // 26: sand.daemon.v1.ResolveAgentLaunchEnvResponse.EnvEntry
}
var file_internal_daemon_daemonpb_daemon_proto_depIdxs = []int32{
	15, // 0: sand.daemon.v1.ResolveAgentLaunchEnvRequest.profile_env:type_name -> sand.daemon.v1.EnvPolicy
	26, // 1: sand.daemon.v1.ResolveAgentLaunchEnvResponse.env:type_name -> sand.daemon.v1.ResolveAgentLaunchEnvResponse.EnvEntry
	16, // 2: sand.daemon.v1.EnvPolicy.files:type_name -> sand.daemon.v1.EnvFileRef
	17, // 3: sand.daemon.v1.EnvPolicy.vars:type_name -> sand.daemon.v1.EnvVarRule
	21, // 4: sand.daemon.v1.CreateSandboxRequest.shared_caches:type_name -> sand.daemon.v1.SharedCacheConfig
	0,  // 5: sand.daemon.v1.DaemonService.Ping:input_type -> sand.daemon.v1.PingRequest
	2,  // 6: sand.daemon.v1.DaemonService.Version:input_type -> sand.daemon.v1.VersionRequest
	5,  // 7: sand.daemon.v1.DaemonService.Shutdown:input_type -> sand.daemon.v1.ShutdownRequest
	6,  // 8: sand.daemon.v1.DaemonService.LogSandbox:input_type -> sand.daemon.v1.IDRequest
	8,  // 9: sand.daemon.v1.DaemonService.ListSandboxes:input_type -> sand.daemon.v1.ListSandboxesRequest
	6,  // 10: sand.daemon.v1.DaemonService.GetSandbox:input_type -> sand.daemon.v1.IDRequest
	6,  // 11: sand.daemon.v1.DaemonService.RemoveSandbox:input_type -> sand.daemon.v1.IDRequest
	6,  // 12: sand.daemon.v1.DaemonService.StopSandbox:input_type -> sand.daemon.v1.IDRequest
	11, // 13: sand.daemon.v1.DaemonService.StartSandbox:input_type -> sand.daemon.v1.StartSandboxRequest
	6,  // 14: sand.daemon.v1.DaemonService.SyncHostGitMirror:input_type -> sand.daemon.v1.IDRequest
	13, // 15: sand.daemon.v1.DaemonService.ResolveAgentLaunchEnv:input_type -> sand.daemon.v1.ResolveAgentLaunchEnvRequest
	18, // 16: sand.daemon.v1.DaemonService.ExportImage:input_type -> sand.daemon.v1.ExportImageRequest
	19, // 17: sand.daemon.v1.DaemonService.Stats:input_type -> sand.daemon.v1.StatsRequest
	6,  // 18: sand.daemon.v1.DaemonService.VSC:input_type -> sand.daemon.v1.IDRequest
	22, // 19: sand.daemon.v1.DaemonService.CreateSandbox:input_type -> sand.daemon.v1.CreateSandboxRequest
	24, // 20: sand.daemon.v1.DaemonService.EnsureImage:input_type -> sand.daemon.v1.EnsureImageRequest
	1,  // 21: sand.daemon.v1.DaemonService.Ping:output_type -> sand.daemon.v1.PingResponse
	3,  // 22: sand.daemon.v1.DaemonService.Version:output_type -> sand.daemon.v1.VersionResponse
	4,  // 23: sand.daemon.v1.DaemonService.Shutdown:output_type -> sand.daemon.v1.StatusResponse
	7,  // 24: sand.daemon.v1.DaemonService.LogSandbox:output_type -> sand.daemon.v1.LogSandboxResponse
	9,  // 25: sand.daemon.v1.DaemonService.ListSandboxes:output_type -> sand.daemon.v1.ListSandboxesResponse
	10, // 26: sand.daemon.v1.DaemonService.GetSandbox:output_type -> sand.daemon.v1.GetSandboxResponse
	4,  // 27: sand.daemon.v1.DaemonService.RemoveSandbox:output_type -> sand.daemon.v1.StatusResponse
	4,  // 28: sand.daemon.v1.DaemonService.StopSandbox:output_type -> sand.daemon.v1.StatusResponse
	4,  // 29: sand.daemon.v1.DaemonService.StartSandbox:output_type -> sand.daemon.v1.StatusResponse
	12, // 30: sand.daemon.v1.DaemonService.SyncHostGitMirror:output_type -> sand.daemon.v1.SyncHostGitMirrorResponse
	14, // 31: sand.daemon.v1.DaemonService.ResolveAgentLaunchEnv:output_type -> sand.daemon.v1.ResolveAgentLaunchEnvResponse
	4,  // 32: sand.daemon.v1.DaemonService.ExportImage:output_type -> sand.daemon.v1.StatusResponse
	20, // 33: sand.daemon.v1.DaemonService.Stats:output_type -> sand.daemon.v1.StatsResponse
	4,  // 34: sand.daemon.v1.DaemonService.VSC:output_type -> sand.daemon.v1.StatusResponse
	23, // 35: sand.daemon.v1.DaemonService.CreateSandbox:output_type -> sand.daemon.v1.CreateSandboxResponse
	25, // 36: sand.daemon.v1.DaemonService.EnsureImage:output_type -> sand.daemon.v1.EnsureImageResponse
	21, // [21:37] is the sub-list for method output_type
	5,  // [5:21] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_daemon_daemonpb_daemon_proto_init() }
func file_internal_daemon_daemonpb_daemon_proto_init() {
	if File_internal_daemon_daemonpb_daemon_proto != nil {
		return
	}
	file_internal_daemon_daemonpb_daemon_proto_msgTypes[23].OneofWrappers = []any{
		(*CreateSandboxResponse_Progress)(nil),
		(*CreateSandboxResponse_BoxJson)(nil),
		(*CreateSandboxResponse_Error)(nil),
	}
	file_internal_daemon_daemonpb_daemon_proto_msgTypes[25].OneofWrappers = []any{
		(*EnsureImageResponse_Progress)(nil),
		(*EnsureImageResponse_Error)(nil),
		(*EnsureImageResponse_Ok)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_daemon_daemonpb_daemon_proto_rawDesc), len(file_internal_daemon_daemonpb_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_daemon_daemonpb_daemon_proto_goTypes,
		DependencyIndexes: file_internal_daemon_daemonpb_daemon_proto_depIdxs,
		MessageInfos:      file_internal_daemon_daemonpb_daemon_proto_msgTypes,
	}.Build()
	File_internal_daemon_daemonpb_daemon_proto = out.File
	file_internal_daemon_daemonpb_daemon_proto_goTypes = nil
	file_internal_daemon_daemonpb_daemon_proto_depIdxs = nil
}
