// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: internal/daemon/daemonpb/daemon.proto

package daemonpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_Ping_FullMethodName                  = "/sand.daemon.v1.DaemonService/Ping"
	DaemonService_Version_FullMethodName               = "/sand.daemon.v1.DaemonService/Version"
	DaemonService_Shutdown_FullMethodName              = "/sand.daemon.v1.DaemonService/Shutdown"
	DaemonService_LogSandbox_FullMethodName            = "/sand.daemon.v1.DaemonService/LogSandbox"
	DaemonService_ListSandboxes_FullMethodName         = "/sand.daemon.v1.DaemonService/ListSandboxes"
	DaemonService_GetSandbox_FullMethodName            = "/sand.daemon.v1.DaemonService/GetSandbox"
	DaemonService_RemoveSandbox_FullMethodName         = "/sand.daemon.v1.DaemonService/RemoveSandbox"
	DaemonService_StopSandbox_FullMethodName           = "/sand.daemon.v1.DaemonService/StopSandbox"
	DaemonService_StartSandbox_FullMethodName          = "/sand.daemon.v1.DaemonService/StartSandbox"
	DaemonService_SyncHostGitMirror_FullMethodName     = "/sand.daemon.v1.DaemonService/SyncHostGitMirror"
	DaemonService_ResolveAgentLaunchEnv_FullMethodName = "/sand.daemon.v1.DaemonService/ResolveAgentLaunchEnv"
	DaemonService_ExportImage_FullMethodName           = "/sand.daemon.v1.DaemonService/ExportImage"
	DaemonService_Stats_FullMethodName                 = "/sand.daemon.v1.DaemonService/Stats"
	DaemonService_VSC_FullMethodName                   = "/sand.daemon.v1.DaemonService/VSC"
	DaemonService_CreateSandbox_FullMethodName         = "/sand.daemon.v1.DaemonService/CreateSandbox"
	DaemonService_EnsureImage_FullMethodName           = "/sand.daemon.v1.DaemonService/EnsureImage"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	LogSandbox(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*LogSandboxResponse, error)
	ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error)
	GetSandbox(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*GetSandboxResponse, error)
	RemoveSandbox(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	StopSandbox(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	StartSandbox(ctx context.Context, in *StartSandboxRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	SyncHostGitMirror(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*SyncHostGitMirrorResponse, error)
	ResolveAgentLaunchEnv(ctx context.Context, in *ResolveAgentLaunchEnvRequest, opts ...grpc.CallOption) (*ResolveAgentLaunchEnvResponse, error)
	ExportImage(ctx context.Context, in *ExportImageRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	VSC(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateSandboxResponse], error)
	EnsureImage(ctx context.Context, in *EnsureImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnsureImageResponse], error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, DaemonService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, DaemonService_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) LogSandbox(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*LogSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogSandboxResponse)
	err := c.cc.Invoke(ctx, DaemonService_LogSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxesResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListSandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetSandbox(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*GetSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSandboxResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) RemoveSandbox(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_RemoveSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopSandbox(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_StopSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartSandbox(ctx context.Context, in *StartSandboxRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_StartSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) SyncHostGitMirror(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*SyncHostGitMirrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncHostGitMirrorResponse)
	err := c.cc.Invoke(ctx, DaemonService_SyncHostGitMirror_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ResolveAgentLaunchEnv(ctx context.Context, in *ResolveAgentLaunchEnvRequest, opts ...grpc.CallOption) (*ResolveAgentLaunchEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAgentLaunchEnvResponse)
	err := c.cc.Invoke(ctx, DaemonService_ResolveAgentLaunchEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ExportImage(ctx context.Context, in *ExportImageRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_ExportImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, DaemonService_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) VSC(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_VSC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateSandboxResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[0], DaemonService_CreateSandbox_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateSandboxRequest, CreateSandboxResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_CreateSandboxClient = grpc.ServerStreamingClient[CreateSandboxResponse]

func (c *daemonServiceClient) EnsureImage(ctx context.Context, in *EnsureImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnsureImageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[1], DaemonService_EnsureImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EnsureImageRequest, EnsureImageResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_EnsureImageClient = grpc.ServerStreamingClient[EnsureImageResponse]

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
type DaemonServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*StatusResponse, error)
	LogSandbox(context.Context, *IDRequest) (*LogSandboxResponse, error)
	ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error)
	GetSandbox(context.Context, *IDRequest) (*GetSandboxResponse, error)
	RemoveSandbox(context.Context, *IDRequest) (*StatusResponse, error)
	StopSandbox(context.Context, *IDRequest) (*StatusResponse, error)
	StartSandbox(context.Context, *StartSandboxRequest) (*StatusResponse, error)
	SyncHostGitMirror(context.Context, *IDRequest) (*SyncHostGitMirrorResponse, error)
	ResolveAgentLaunchEnv(context.Context, *ResolveAgentLaunchEnvRequest) (*ResolveAgentLaunchEnvResponse, error)
	ExportImage(context.Context, *ExportImageRequest) (*StatusResponse, error)
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	VSC(context.Context, *IDRequest) (*StatusResponse, error)
	CreateSandbox(*CreateSandboxRequest, grpc.ServerStreamingServer[CreateSandboxResponse]) error
	EnsureImage(*EnsureImageRequest, grpc.ServerStreamingServer[EnsureImageResponse]) error
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDaemonServiceServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedDaemonServiceServer) Shutdown(context.Context, *ShutdownRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDaemonServiceServer) LogSandbox(context.Context, *IDRequest) (*LogSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogSandbox not implemented")
}
func (UnimplementedDaemonServiceServer) ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSandboxes not implemented")
}
func (UnimplementedDaemonServiceServer) GetSandbox(context.Context, *IDRequest) (*GetSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandbox not implemented")
}
func (UnimplementedDaemonServiceServer) RemoveSandbox(context.Context, *IDRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSandbox not implemented")
}
func (UnimplementedDaemonServiceServer) StopSandbox(context.Context, *IDRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSandbox not implemented")
}
func (UnimplementedDaemonServiceServer) StartSandbox(context.Context, *StartSandboxRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSandbox not implemented")
}
func (UnimplementedDaemonServiceServer) SyncHostGitMirror(context.Context, *IDRequest) (*SyncHostGitMirrorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncHostGitMirror not implemented")
}
func (UnimplementedDaemonServiceServer) ResolveAgentLaunchEnv(context.Context, *ResolveAgentLaunchEnvRequest) (*ResolveAgentLaunchEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAgentLaunchEnv not implemented")
}
func (UnimplementedDaemonServiceServer) ExportImage(context.Context, *ExportImageRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportImage not implemented")
}
func (UnimplementedDaemonServiceServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedDaemonServiceServer) VSC(context.Context, *IDRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VSC not implemented")
}
func (UnimplementedDaemonServiceServer) CreateSandbox(*CreateSandboxRequest, grpc.ServerStreamingServer[CreateSandboxResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedDaemonServiceServer) EnsureImage(*EnsureImageRequest, grpc.ServerStreamingServer[EnsureImageResponse]) error {
	return status.Error(codes.Unimplemented, "method EnsureImage not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_LogSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).LogSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_LogSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).LogSandbox(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListSandboxes(ctx, req.(*ListSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetSandbox(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_RemoveSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).RemoveSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_RemoveSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).RemoveSandbox(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopSandbox(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartSandbox(ctx, req.(*StartSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_SyncHostGitMirror_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).SyncHostGitMirror(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_SyncHostGitMirror_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).SyncHostGitMirror(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ResolveAgentLaunchEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAgentLaunchEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ResolveAgentLaunchEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ResolveAgentLaunchEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ResolveAgentLaunchEnv(ctx, req.(*ResolveAgentLaunchEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ExportImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ExportImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ExportImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ExportImage(ctx, req.(*ExportImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_VSC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).VSC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_VSC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).VSC(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CreateSandbox_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateSandboxRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).CreateSandbox(m, &grpc.GenericServerStream[CreateSandboxRequest, CreateSandboxResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_CreateSandboxServer = grpc.ServerStreamingServer[CreateSandboxResponse]

func _DaemonService_EnsureImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EnsureImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).EnsureImage(m, &grpc.GenericServerStream[EnsureImageRequest, EnsureImageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_EnsureImageServer = grpc.ServerStreamingServer[EnsureImageResponse]

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sand.daemon.v1.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _DaemonService_Ping_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _DaemonService_Version_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _DaemonService_Shutdown_Handler,
		},
		{
			MethodName: "LogSandbox",
			Handler:    _DaemonService_LogSandbox_Handler,
		},
		{
			MethodName: "ListSandboxes",
			Handler:    _DaemonService_ListSandboxes_Handler,
		},
		{
			MethodName: "GetSandbox",
			Handler:    _DaemonService_GetSandbox_Handler,
		},
		{
			MethodName: "RemoveSandbox",
			Handler:    _DaemonService_RemoveSandbox_Handler,
		},
		{
			MethodName: "StopSandbox",
			Handler:    _DaemonService_StopSandbox_Handler,
		},
		{
			MethodName: "StartSandbox",
			Handler:    _DaemonService_StartSandbox_Handler,
		},
		{
			MethodName: "SyncHostGitMirror",
			Handler:    _DaemonService_SyncHostGitMirror_Handler,
		},
		{
			MethodName: "ResolveAgentLaunchEnv",
			Handler:    _DaemonService_ResolveAgentLaunchEnv_Handler,
		},
		{
			MethodName: "ExportImage",
			Handler:    _DaemonService_ExportImage_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _DaemonService_Stats_Handler,
		},
		{
			MethodName: "VSC",
			Handler:    _DaemonService_VSC_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateSandbox",
			Handler:       _DaemonService_CreateSandbox_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EnsureImage",
			Handler:       _DaemonService_EnsureImage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/daemon/daemonpb/daemon.proto",
}
