-- Code generated by go generate; DO NOT EDIT.
-- Source of truth: internal/db/migrations/*.up.sql.

CREATE TABLE sandboxes (
    id TEXT PRIMARY KEY,
    container_id TEXT,
    host_origin_dir TEXT NOT NULL,
    sandbox_work_dir TEXT NOT NULL,
    image_name TEXT NOT NULL,
    dns_domain TEXT,
    env_file TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    agent_type TEXT DEFAULT 'default',
    original_git_origin TEXT,
    original_git_branch TEXT,
    original_git_commit TEXT,
    original_git_is_dirty BOOLEAN NOT NULL DEFAULT 0,
    allowed_domains TEXT,
    cpu INT,
    memory_mb INT,
    default_username TEXT,
    default_uid TEXT,
    name TEXT NOT NULL DEFAULT '',
    state TEXT NOT NULL DEFAULT 'active',
    deleted_at DATETIME,
    trash_work_dir TEXT,
    profile_name TEXT,
    mount_specs TEXT,
    container_bootstrapped BOOLEAN NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX idx_active_sandbox_name ON sandboxes(name) WHERE state = 'active';

CREATE INDEX idx_container_id ON sandboxes(container_id);

CREATE INDEX idx_sandboxes_state ON sandboxes(state);
