package main

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	_ "modernc.org/sqlite"
)

const outputHeader = `-- Code generated by go generate; DO NOT EDIT.
-- Source of truth: internal/db/migrations/*.up.sql.

`

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		return fmt.Errorf("open in-memory sqlite database: %w", err)
	}
	defer db.Close()
	db.SetMaxOpenConns(1)

	dbDir, err := dbSourceDir()
	if err != nil {
		return err
	}

	migrations, err := filepath.Glob(filepath.Join(dbDir, "migrations", "*.up.sql"))
	if err != nil {
		return fmt.Errorf("find migration files: %w", err)
	}
	sort.Strings(migrations)

	for _, migration := range migrations {
		contents, err := os.ReadFile(migration)
		if err != nil {
			return fmt.Errorf("read %s: %w", migration, err)
		}
		if strings.TrimSpace(string(contents)) == "" {
			continue
		}
		if _, err := db.Exec(string(contents)); err != nil {
			return fmt.Errorf("apply %s: %w", migration, err)
		}
	}

	schema, err := dumpSchema(db)
	if err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(dbDir, "schema.sql"), []byte(outputHeader+schema), 0o644); err != nil {
		return fmt.Errorf("write schema.sql: %w", err)
	}

	return nil
}

func dbSourceDir() (string, error) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("locate generator source")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", "..")), nil
}

func dumpSchema(db *sql.DB) (string, error) {
	tables, err := tableStatements(db)
	if err != nil {
		return "", err
	}

	indexes, err := indexStatements(db)
	if err != nil {
		return "", err
	}

	statements := append(tables, indexes...)
	return strings.Join(statements, "\n\n") + "\n", nil
}

func tableStatements(db *sql.DB) ([]string, error) {
	rows, err := db.Query(`
SELECT name
FROM sqlite_schema
WHERE type = 'table'
  AND name NOT LIKE 'sqlite_%'
ORDER BY name;
`)
	if err != nil {
		return nil, fmt.Errorf("query sqlite tables: %w", err)
	}
	defer rows.Close()

	var tables []string
	for rows.Next() {
		var table string
		if err := rows.Scan(&table); err != nil {
			return nil, fmt.Errorf("scan table name: %w", err)
		}
		tables = append(tables, table)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate table names: %w", err)
	}
	if err := rows.Close(); err != nil {
		return nil, fmt.Errorf("close table names: %w", err)
	}

	var statements []string
	for _, table := range tables {
		statement, err := createTableStatement(db, table)
		if err != nil {
			return nil, err
		}
		statements = append(statements, statement)
	}

	return statements, nil
}

func createTableStatement(db *sql.DB, table string) (string, error) {
	rows, err := db.Query(`
SELECT cid, name, type, "notnull", dflt_value, pk
FROM pragma_table_info(?)
ORDER BY cid;
`, table)
	if err != nil {
		return "", fmt.Errorf("query columns for %s: %w", table, err)
	}
	defer rows.Close()

	var columns []string
	for rows.Next() {
		var (
			cid     int
			name    string
			colType sql.NullString
			notNull int
			dflt    sql.NullString
			pk      int
		)
		if err := rows.Scan(&cid, &name, &colType, &notNull, &dflt, &pk); err != nil {
			return "", fmt.Errorf("scan column for %s: %w", table, err)
		}

		parts := []string{formatIdent(name)}
		if colType.Valid && colType.String != "" {
			parts = append(parts, colType.String)
		}
		if pk > 0 {
			parts = append(parts, "PRIMARY KEY")
		}
		if notNull != 0 {
			parts = append(parts, "NOT NULL")
		}
		if dflt.Valid {
			parts = append(parts, "DEFAULT", dflt.String)
		}

		columns = append(columns, "    "+strings.Join(parts, " "))
	}
	if err := rows.Err(); err != nil {
		return "", fmt.Errorf("iterate columns for %s: %w", table, err)
	}
	if len(columns) == 0 {
		return "", fmt.Errorf("table %s has no columns", table)
	}

	return fmt.Sprintf("CREATE TABLE %s (\n%s\n);", formatIdent(table), strings.Join(columns, ",\n")), nil
}

func indexStatements(db *sql.DB) ([]string, error) {
	rows, err := db.Query(`
SELECT sql
FROM sqlite_schema
WHERE sql IS NOT NULL
  AND type = 'index'
  AND name NOT LIKE 'sqlite_%'
ORDER BY name;
`)
	if err != nil {
		return nil, fmt.Errorf("query sqlite indexes: %w", err)
	}
	defer rows.Close()

	var statements []string
	for rows.Next() {
		var statement string
		if err := rows.Scan(&statement); err != nil {
			return nil, fmt.Errorf("scan index statement: %w", err)
		}
		statements = append(statements, strings.TrimRight(statement, ";")+";")
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate index statements: %w", err)
	}

	return statements, nil
}

func quoteIdent(name string) string {
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}

func formatIdent(name string) string {
	if isBareIdent(name) {
		return name
	}
	return quoteIdent(name)
}

func isBareIdent(name string) bool {
	for i, r := range name {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= 'A' && r <= 'Z':
		case r == '_':
		case i > 0 && r >= '0' && r <= '9':
		default:
			return false
		}
	}
	return name != ""
}
